version: '3.8'
services:
  nginx:
    build:
      context: ./frontend
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - react-frontend
      - springboot-backend

  react-frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    working_dir: /app

  springboot-backend:
    build:
      context: ./backend
    container_name: springboot-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/carry_guides_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      FRONT_END_URL: http://localhost
      BASE_URL: http://localhost
    depends_on:
      - db
    entrypoint: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "target/carry_guide_admin-0.0.1-SNAPSHOT.jar"]

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carry_guides_db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: